version: '3.8'

services:
  workspace:
    build: .
    container_name: Workspace
    ports:
      - "5000:8080"
    env_file: 
      - ./config/config.env
    volumes:
      - ./templates:/app/templates
      - ./static:/app/static
    stdin_open: true
    tty: true
    restart: always
    environment:
      - TZ=America/Sao_Paulo
