"""V1.0.0 RELEASE

Revision ID: d04224004d7d
Revises: 
Create Date: 2025-02-21 08:47:40.907349

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd04224004d7d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth')
    op.drop_table('history_login')
    op.drop_table('auth_inatividade')
    with op.batch_alter_table('log_actions', schema=None) as batch_op:
        batch_op.drop_index('FK_AUTH_USERNAME_idx')

    op.drop_table('log_actions')
    op.drop_table('log_updates')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_updates',
    sa.Column('ID_log_update', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('last_update', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('ID_log_update'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('log_actions',
    sa.Column('ID_log', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('ID_auth', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('username', mysql.VARCHAR(length=244), nullable=True),
    sa.Column('estado', mysql.TEXT(), nullable=True),
    sa.Column('diario', mysql.TEXT(), nullable=True),
    sa.Column('complemento', mysql.TINYINT(), autoincrement=False, nullable=True),
    sa.Column('status', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('inicio', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('fim', mysql.TIMESTAMP(), nullable=True),
    sa.Column('tempo_decorrido', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('ID_log'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('log_actions', schema=None) as batch_op:
        batch_op.create_index('FK_AUTH_USERNAME_idx', ['username'], unique=False)

    op.create_table('auth_inatividade',
    sa.Column('ID_inatividade', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('ID_auth', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('ID_log', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('tempo_inatividade', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('data', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('ID_inatividade'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('history_login',
    sa.Column('ID_history', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('ID_auth', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=True),
    sa.Column('Data_login', mysql.DATETIME(), nullable=True),
    sa.Column('Data_logout', mysql.DATETIME(), nullable=True),
    sa.Column('Created_date', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['ID_auth'], ['auth.ID_auth'], name='FK_AUTH_LOGIN'),
    sa.PrimaryKeyConstraint('ID_history'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('auth',
    sa.Column('ID_auth', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=244), nullable=False),
    sa.Column('password', mysql.TEXT(), nullable=False),
    sa.Column('role', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('origin', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=1), server_default=sa.text("'L'"), nullable=False),
    sa.Column('status_logado', mysql.VARCHAR(length=1), server_default=sa.text("'N'"), nullable=False),
    sa.Column('created_by', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('modified_by', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('last_login', mysql.DATETIME(), nullable=True),
    sa.Column('last_logout', mysql.DATETIME(), nullable=True),
    sa.Column('created_date', mysql.DATETIME(), nullable=False),
    sa.Column('modified_date', mysql.DATETIME(), nullable=False),
    sa.Column('deleted', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ID_auth'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
